include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    avoid_print: true
    use_super_parameters: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    unnecessary_null_checks: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

analyzer:
  errors:
    # Treat missing returns as errors, not just warnings
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
